const ROLES = {
  DOCTOR: 'DOCTOR',
  NURSE_RECEPTIONIST: 'NURSE_RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  ADMIN: 'ADMIN',
  PATIENT: 'PATIENT',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  CLERICAL_ASSISTANT: 'CLERICAL_ASSISTANT'
};

export default ROLES;