const ROLES = {
  RECEPTIONIST: 'RECEPTIONIST',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  PHARMACIST: 'PHARMACIST',
  ADMIN: 'ADMIN',
  PATIENT: 'PATIENT',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN'
};

export default ROLES;